### ISSUE TITLE
.dump causes an error

### ISSUE THREAD

**Issue by brun0ne** [tursodatabase/libsql-shell-go#166]
I have a db hosted on Turso.
After cloning and building I ran:

`./main libsql://<libname>.turso.io --auth='<token>'`

Then:

`.dump`

And got an error:

`Error: Get "libsql://<libname>/dump": unsupported protocol scheme "libsql"`

Is this intended? How to dump a db using this tool?

**Comment by haaawk** [comment]
Does  ./main https://<libname>.turso.io --auth='<token>' work?

**Comment by brun0ne** [comment]
Yes, thank you! I think the "Query a Turso database" section of readme is a bit outdated (`?authToken=` does not work, and it says to use `libsql://`), but my issue is resolved.
